In [5]:
import pandas as pd
import numpy as np

In [15]:
data = np.array([1,2,4,5,8])
label = ["Vishal","Tom","A","B","C"]

pd.Series(data,index = label)

Vishal    1
Tom       2
A         4
B         5
C         8
dtype: int32

In [2]:
data2 = {
    "Name": ["Vishal","Raj","Ali","Emma"],
    "Rollno" : [1,2,5,7],
    "Marks" : [100,90,33,67]
}

pd.DataFrame(data2)

     Name  Rollno  Marks
0  Vishal       1    100
1     Raj       2     90
2     Ali       5     33
3    Emma       7     67

In [6]:
data = pd.read_csv("heart_data.csv")
data

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [12]:
data.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
       'DEATH_EVENT'],
      dtype='object')

In [29]:
data.loc[2]

age                             65.0
anaemia                          0.0
creatinine_phosphokinase       146.0
diabetes                         0.0
ejection_fraction               20.0
high_blood_pressure              0.0
platelets                   162000.0
serum_creatinine                 1.3
serum_sodium                   129.0
sex                              1.0
smoking                          1.0
time                             7.0
DEATH_EVENT                      1.0
Name: 2, dtype: float64

In [38]:
data.loc[1,"creatinine_phosphokinase"]

7861

In [39]:
data.iloc[1 , 2]

7861

In [ ]:
data.loc[1:4]

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [ ]:
data.iloc[1:5]

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [10]:
data.loc[1:4 , "age":"platelets" ]

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets
1,55.0,0,7861,0,38,0,263358.03
2,65.0,0,146,0,20,0,162000.00
3,50.0,1,111,0,20,0,210000.00
4,65.0,1,160,1,20,0,327000.00

In [11]:
data.iloc[1:5 , 0: 7 ]

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets
1,55.0,0,7861,0,38,0,263358.03
2,65.0,0,146,0,20,0,162000.00
3,50.0,1,111,0,20,0,210000.00
4,65.0,1,160,1,20,0,327000.00

In [14]:
data.iloc[0:5, 1]

0    0
1    0
2    0
3    1
4    1
Name: anaemia, dtype: int64

In [15]:
data.loc[0:4 , "age"]

0    75.0
1    55.0
2    65.0
3    50.0
4    65.0
Name: age, dtype: float64